Use warnings.warn instead of raising UserWarning
byteskeptical/sftpretty pull request #19
Opened 2023-01-11 21:31 UTC by coreyhartley

I've recently replaced this dependency with `pysftp` in a repo of ours.  In our code we do the following:
```
self.cnopts = CnOpts()
self.cnopts.hostkeys = None
```
This causes the follwing error in our tests:
![sftpretty_error](https://user-images.githubusercontent.com/83661242/211920349-71f4243a-9083-4049-b5a8-63ed44f48cd8.png)

The issue is that we cannot set `cnopts.hostkeys = None` due to the `UserWarning` being raised in the constructor, therefore not allowing us to create the object in the first place.  In order to rectify this, I have updated the use of raising `UserWarning` to fire `warnings.warn` instead.  This should ensure that this warning message will not break the constructor going forward.  

Note that in my repo, ubuntu's python 3.6 was unble to be found in the cache.  Not sure what needs to be done there.

2023-01-13 01:35 UTC, byteskeptical commented
Python 3.6 has been end of life since 12/2021. It's supported mainly because it's still relatively straight forward to maintain at the moment.  I see the issue, though I'm surprised your running into it on a linux distro. The raise is quite deliberate. Having host key verification enabled by default is the desired behavior. You can disable it, though not recommended. I'm providing a PR to your PR with the changes necessary to fix the issue without disabling verification by default. Test it out and if that works for you merge it so I can accept this PR.

2023-01-16 21:04 UTC, coreyhartley commented
I merged your changes on my end, the only things I had to update was the warning string format and the `None` check in one of the tests.

Otherwise, thanks for looking into everything and making those updates!  My intention calling `warn` instead of raising was only to keep the original functionality from `pysftp`, but I think that this works better.

I did not alter the Ubuntu-py3.6 in the test at all, otherwise everything else is green now.

2023-01-17 02:56 UTC, byteskeptical requested changes

2023-01-17 02:56 UTC, byteskeptical commented on tests/test_remote_server_key.py
> +        with pytest.warns(UserWarning):
This needs to be switched back to raises.

2023-01-17 02:56 UTC, byteskeptical commented on sftpretty/__init__.py
> +from warnings import warn
No need for this import.

2023-01-17 16:28 UTC, byteskeptical requested changes
Looks good, thank you! One last request can you remove 3.6 from test.yml and add 3.11?

2023-01-17 17:06 UTC, coreyhartley commented
> Looks good, thank you! One last request can you remove 3.6 from test.yml and add 3.11?

Absolutely!

2023-01-17 18:09 UTC, byteskeptical approved these changes
ok byteskeptical@

2023-01-17 18:12 UTC, merged